### ISSUE TITLE
配合Popup使用会崩溃

### ISSUE THREAD

**Issue by jyj234** [188080501/JQImageItem#1]
是不是没有针对这个进行处理

**Comment by 188080501** [comment]
是直接运行代码，然后缩放窗口就会崩溃吗？你是什么环境和系统？
在我的测试环境中，缩放主窗口是正常的，我需要更多的信息来判断这个问题，方便时请提供下

**Comment by jyj234** [comment]
import QtQuick 2.15
import QtQuick.Window 2.15
import QtQuick.Controls 2.15
import JQImageItem 1.0

Window {
    id: window
    width: 720
    height: 720
    visible: true
    color: "#eef3fa"

    Component.onDestruction: {
        Helper.stop();
    }

    Popup{
        id: popup
        y: 100
        width: parent.width
        height: parent.height - 100
        JQImageItem {
            id: imageItem
            anchors.fill: parent
            visible: false
        }

        JQImageItem2 {
            id: imageItem2
            anchors.fill: parent
            visible: false
        }
        Component.onCompleted: {
            popup.open()
        }
    }

    MouseArea {
        Button{
            height: 100
            width: 100
            onClicked: {
                if(popup.visible)
                    popup.close()
                else
                    popup.open()
            }
        }
        anchors.fill: parent

        function update() {
            // imageItem.visible  = !imageItem.visible;
            // imageItem2.visible = !imageItem.visible;

            // // 根据visible属性，激活对应的控件
            // if ( imageItem.visible )
            // {
            //     Helper.setImageItem( imageItem );
            //     Helper.setImageItem2( null );
            // }
            // else
            // {
            //     Helper.setImageItem( null );
            //     Helper.setImageItem2( imageItem2 );
            // }
        }

        onClicked: {
            update();
        }

        Component.onCompleted: {
            imageItem.visible = true
            Helper.setImageItem( imageItem )
            // update();
        }
    }
    Text {
        x: 15
        y: 15
        font.pixelSize: 15
        color: "#ff00ff"
        text: {
            var result = "";

            result += window.width.toString();
            result += " x ";
            result += window.height.toString();

            if ( imageItem.visible )
            {
                result += "\nJQImageItem";
            }
            else if ( imageItem2.visible )
            {
                result += "\nJQImageItem2";
            }

            return result;
        }
    }
}
我发现了，是popup的问题，把popup套在imageitem的外面，然后通过按钮去打开关闭popup，就会崩

**Comment by jyj234** [comment]
我认为是打开关闭popup时，会触发createRenderer，这时执行了第二次init，才会崩，我改为这样QQuickFramebufferObject::Renderer *JQImageItem::createRenderer() const
{
    renderer_ = new JQImageItemRenderer();
    renderer_->init();

    return renderer_;
}，但第二次setImage时会阻塞在mutex，我找不到哪里有在lock

**Comment by jyj234** [comment]
之前说的放大崩溃是我根据其他QQuickFramebufferObject的代码去修改了之后，解决了上述问题，但在放大时会崩溃，代码如下https://github.com/jyj234/imageitem

**Comment by 188080501** [comment]
我去看下这个

**Comment by 188080501** [comment]
问题已修复，感谢反馈
https://github.com/188080501/JQImageItem/commit/ce7ba56de95766a736f04cd45bb257a18458f75b

**Comment by jyj234** [comment]
第二次打开popup后setimage会阻塞解决了吗，我这里还是有
https://paste.ubuntu.com/p/dgKNzSJgnd/ ，其中setimageitem改掉了
void Helper::setImageItem(JQImageItem *imageItem)
{
    if ( imageItem )
    {
        imageItem->setImage( QImage( ":/images/1.png" ) );
    }
    imageItem_ = imageItem;
}

**Comment by 188080501** [comment]
修改后可以反复打开了，就用的你发的代码（main.qml）

**Comment by jyj234** [comment]
是我17分钟前发的代码吗，setimageitem有改吗

**Comment by 188080501** [comment]
setimageitem 没有修改，你先拉下最新的代码看看

**Comment by jyj234** [comment]
因为qml里面改不了image，所以我是通过setimageitem修改image，如果不改是没有修改的。我是用最新的试了

**Comment by jyj234** [comment]
确实不崩溃了，但是后续setimage会阻塞

**Comment by 188080501** [comment]
你是Ubuntu系统对吧，看起来是平台差异导致的，可以尝试下这个代码，看看有没有用
修改JQImageItemRenderer的构造函数，让互斥锁支持递归

```
    JQImageItemRenderer():
        mutex_( QMutex::Recursive )
    { }
```

**Comment by jyj234** [comment]
是windows10，qt6.5.2，运行这个程序，点击close再点击open button，应该就能复现出来，https://github.com/jyj234/imageitem.git

**Comment by jyj234** [comment]
把popup的visible设为false后，会销毁JQImageItemRenderer，这时再setImageItem，即使代码中有判断!renderer_，但因为无法将指针设为NULL，所以也是没用的。就算是先将popup.open，再setImage，因为createrender没有同步调用，所以也会有问题

**Comment by jyj234** [comment]
void JQImageItemRenderer::synchronize(QQuickFramebufferObject* item)我建议在这个函数中将QImage写入buffer，这样可以保证render是存在的。因为调用update后，当render被创建后才会进入synchronize

**Comment by 188080501** [comment]
之前写逻辑有点问题，能复现了

**Comment by 188080501** [comment]
方便的话帮忙测试下最新的版本，我在renderer_析构的时候加了设置nullptr的操作，确保了指针的正确
